import type { Metadata } from "next";
import React, { useCallback } from 'react';
import { Roboto } from "next/font/google"
import "./globals.css";
import FontawesomeConfig from "@/fontawesome";

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "NotaForte",
  description: "Generated by NotaFort",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontawesomeConfig />
      </head>
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
