import type { Metadata } from "next";
import React from 'react';
import { Roboto } from "next/font/google"
import "./globals.css";
import FontawesomeConfig from "@/fontawesome";
import Header from "./components/Header";
import SideBar from "./components/SideBar";
import Footer from "./components/Footer";

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "NotaForte",
  description: "Generated by NotaFort",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontawesomeConfig />
      </head>
      <body className={roboto.className}>
        <div className="relative w-full h-screen flex flex-col bg-black  p-0 md:p-1.5">
          <div className="relative w-full h-full flex flex-col">
            <div className="relative w-full m-0 h-full  flex flex-row-reverse pb-20">
              <div className="relative w-full m-0 h-full  flex flex-row-reverse p-0 md:pb-1.5">
                <div className="relative w-full h-full flex flex-col ">
                  <Header />
                  {children}
                </div>
                <SideBar />
              </div>
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
